### ISSUE TITLE
Invalid Arch installtion instructions

### ISSUE THREAD

**Issue by keddad** [VSCodium/vscodium.github.io#19]
There are instructions for Arch on the website suggesting to install _vscodium_ package from AUR, like 
`sudo yay -S vscodium`
But there are no such package! I guess it should be [vscodium-bin](https://aur.archlinux.org/packages/vscodium-bin/).

**Comment by stripedpajamas** [comment]
I think this is already done:

![image](https://user-images.githubusercontent.com/2707340/95773555-8e1d7680-0c73-11eb-9ee0-185f3e91d999.png)
