### ISSUE TITLE
https://vscodium.com/ code snipets are poorly readable (pale text on pale bacgkround)

### ISSUE THREAD

**Issue by matkoniecz** [VSCodium/vscodium.github.io#30]
**Describe the bug**
https://vscodium.com/ code snipets are poorly readable (pale text on pale bacgkround)

**Please confirm that this problem is VSCodium-specific**
It is about VSCodium website and "this site is open source" in footer linked to this repo

**Please confirm that the issue/resolution isn't already documented**
- [x] I checked [the Docs page](https://github.com/VSCodium/vscodium/blob/master/DOCS.md) and my issue is not mentioned there.

**To Reproduce**
1. Go to https://vscodium.com/
2. try to read code there

**Expected behavior**
All text on website is readable

**Screenshots**
![screen01](https://user-images.githubusercontent.com/899988/93661526-b4773a00-fa58-11ea-9aa4-de6910075a4b.png)

**Desktop (please complete the following information):**
 - OS: Lubuntu 20.04
 - Architecture x64
 - Version - not sure how to check deployed version of website

**Additional context**
If "make all text in code snippets 100% black, potentially also make backgrounds closer to white" or "make background 100% black, make all text white" would be accepted and it is fixable by editing CSS file (without some extreme nodejs hell) then I can make a PR.

**Comment by matkoniecz** [comment]
@chadlavi It may be worth reporting as a new issue, this will be closed once this specific visibility issue is fixed.

**Comment by stripedpajamas** [comment]
I merged #25 -- what do you think of it @matkoniecz ?

**Comment by matkoniecz** [comment]
Thanks, it is much better!

But is it useful or necessary to have this dark red color? On dark background it becomes poorly readable in turn and I see no benefit in readability from styling some parameters and `&&` differently.

And if `&&` and long style parameters (note in Arch Linux section that short style parameters are not getting such styling) should be styled specially maybe something less distinct from rest of the text and more distinct from the bacgkround would be better?

![screen02](https://user-images.githubusercontent.com/899988/93846190-ab2ddd80-fca3-11ea-97bd-54e770361847.png)
