### ISSUE TITLE
Modified corrupt Jekyll theme.

### ISSUE THREAD

**Issue by hazarek** [VSCodium/vscodium.github.io#35]
The top menu covers the titles and is not readable.

![Ekran Kaydı 2021-01-25 00 26 13 mov-02F47F4A-59E0-4D4E-98A5-2FB74156BB43](https://user-images.githubusercontent.com/36481442/105644093-c3597780-5ea4-11eb-9a55-cbdc792d2ad7.gif)

# Original theme (SinglePaged)
https://t413.com/SinglePaged/
> Each vertical section sets it’s own color, header icon (or image), title, and easy-to-write markdown body.

<img width="712" alt="Ekran Resmi 2021-01-25 00 28 53" src="https://user-images.githubusercontent.com/36481442/105644240-ae311880-5ea5-11eb-9af4-164eedea2a14.png">

**Comment by elsiehupp** [comment]
FWIW there's also an issue with multi-line code blocks from the Markdown source rendering as a single line. I don't know where the problem originated, but [I reported it as a bug](https://github.com/t413/SinglePaged/issues/72) over at SinglePaged.
