### ISSUE TITLE
Rendered bash code not breaking lines

### ISSUE THREAD

**Issue by billbalm** [VSCodium/vscodium.github.io#49]
Not sure if jekyll's issue but Markdown is not being parsed correctly.

This line should break after \\, but it's not. In this case it would be better to remove the backslashes altogether. Someone not so attentive to details would copy and run this line and not realize it did nothing.

```
wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg \ | gpg --dearmor \ | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
```

**Comment by stripedpajamas** [comment]
Real line breaks added in #52
