### ISSUE TITLE
Error updating VSCodium 

### ISSUE THREAD

**Issue by NonTechieGuides** [VSCodium/vscodium.github.io#58]
I'm on Arch Linux and running yay -Syu to update. However, the install/update fails with the lines: 

```
applying patch: ../patches/use-github-pat.patch
++ [[ linux == \o\s\x ]]
++ CHILD_CONCURRENCY=1
++ yarn --frozen-lockfile
prepare_vscode.sh: line 41: yarn: command not found
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: vscodium
```
I can provide more readout from the command line, if necessary. Not sure what is needed. I tried it three times, including after updating npm, according to a callout box on the 2nd attempt.

**Comment by GitMensch** [comment]
This repository is about the website, you likely wanted to create an issue on https://github.com/VSCodium/vscodium.

In case of Arch it likely is most reasonable to send reports to https://aur.archlinux.org/packages/vscodium-bin (where you can also vote for the package), please do so and retry as there was an update three days ago.
