### ISSUE TITLE
Images are not visible in 2000-01-01-intro.md

### ISSUE THREAD

**Issue by BoseSj** [VSCodium/vscodium.github.io#66]
### Description
Images are not visible in [2000-01-01-intro.md](https://github.com/VSCodium/vscodium.github.io/blob/06fae36d0ccdc30f9f0117afbebc049288e468ae/_posts/2000-01-01-intro.md) file.

### Screenshot 
![image](https://user-images.githubusercontent.com/58129377/193537314-120f42d5-0d61-4508-9ef9-99ab56e42c15.png)

**Comment by daiyam** [comment]
It's a jekyll website so the image is relative to the root the website not of the file.
The image is correctly displayed.
