### ISSUE TITLE
Source of some images are questionable

### ISSUE THREAD

**Issue by lextm** [VSCodium/vscodium.github.io#7]
I happened to notice that some images like https://vscodium.com/img/intellisense.svg seem to be copied from VSCode's website https://code.visualstudio.com/assets/images/home-intellisense.svg. That can be a harmful approach, as it is not clear whether Microsoft releases the images under a permissive license.

You might consider removing such images, and replace with your own.

**Comment by stripedpajamas** [comment]
You're probably right, @lextm. Thanks for catching that. I will try to find some time to clean that up a bit.
