### ISSUE TITLE
change to new icons

### ISSUE THREAD

**Issue by moortaube** [VSCodium/vscodium.github.io#75]
VSCodium icon has changed so it has to be changed here, too.

https://github.com/VSCodium/vscodium/releases/tag/1.77.0.23090

**Comment by GitMensch** [comment]
@daiyam Can you adjust that for the VSCodium "organization" on GH https://github.com/VSCodium or is this something only @stripedpajamas can do?

**Comment by daiyam** [comment]
@GitMensch  done
