### ISSUE TITLE
OpenSuse/SUSE repository not working

### ISSUE THREAD

**Issue by webdeploy-davoli-alessio** [VSCodium/vscodium.github.io#76]
Zypper does not find the version it searches for: `File './vscodium-1.77.0.23093-x86_64.rpm' not found on medium 'https://download.vscodium.com/rpms/`

Using:
`printf "[gitlab.com_paulcarroty_vscodium_repo]\nname=gitlab.com_paulcarroty_vscodium_repo\nbaseurl=https://download.vscodium.com/rpms/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/-/raw/master/pub.gpg\nmetadata_expire=1h" | sudo tee -a /etc/zypp/repos.d/vscodium.repo
`

Is it a version mismatch? Because I find out that the latest version is actually downloadable without any problem.

**Comment by paulcarroty** [comment]
Now it works, probably the outdated cache happened.
