### ISSUE TITLE
Unessential highlighting effect on few elements

### ISSUE THREAD

**Issue by code-reaper08** [VSCodium/vscodium.github.io#77]
Unneeded highlighting for the Download CTA button on the landing page (refer the below screenshot)

![image](https://github.com/VSCodium/vscodium.github.io/assets/64256342/91a1cd49-4775-43c8-89ec-0711c45b070b)

The same effect happens with the shields.io badges as well (refer the screenshot below)
![image](https://github.com/VSCodium/vscodium.github.io/assets/64256342/8984bff8-175a-4581-a83e-90f3b77d95a4)

**Comment by GitMensch** [comment]
Note that this partially contradicts to #72.
Disabling those specific ones LGTM.
