### ISSUE TITLE
https://download.vscodium.com/debs is now inaccessible

### ISSUE THREAD

**Issue by RadxaYuntian** [VSCodium/vscodium.github.io#85]
Currently we use https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs as a workaround.

**Comment by daiyam** [comment]
Duplicate of https://github.com/VSCodium/vscodium/issues/1910

**Comment by daiyam** [comment]
No because gitlab has stricter limits which the CDN resolve. If the gitlab limits are reached, it would limit us to push new updates.
