### ISSUE TITLE
Codium crashes when I click the FILE on the main menu. 

### ISSUE THREAD

**Issue by teklynk** [VSCodium/vscodium.github.io#89]
Codium launches and I can mostly use it. However, when I click FILE on the main menu, I do not get a sub menu and codium crashes and closes. Edit, Selection, View, Go... all seem to be working fine. It is only an issue when I click FILE. This issue appeared after the latest update. I am using Linux Mint 22 and Xorg/X11.

Version: 1.95.1
Release: 24307
Commit: 8798508b6fcf62248291cdf7a7e870bd84f7257d
Date: 2024-11-02T15:11:51.261Z
Electron: 32.2.1
ElectronBuildId: undefined
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-48-generic

**Comment by daiyam** [comment]
duplicate https://github.com/VSCodium/vscodium/issues/2082
