### ISSUE TITLE
download.vscodium.com: The name in the certificate does not match the expected.

### ISSUE THREAD

**Issue by kevinoid** [VSCodium/vscodium.github.io#91]
With an apt source configured according to [the instructions on vscodium.com](https://vscodium.com/#install-on-debian-ubuntu-deb-package), `apt update` produces the following error:

> Warning: Failed to fetch https://download.vscodium.com/debs/dists/vscodium/InRelease  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 2400:52e0:1a01::1002:1 443]
> Warning: Some index files failed to download. They have been ignored, or old ones used instead.

It appears that the certificate used by download.vscodium.com (169.150.236.98 2400:52e0:1a01::1002:1 2400:52e0:1a00:0:0:0:1207:2 and likely others) has `CN=*.b-cdn.net` and `subjectAltName: *.b-cdn.net b-cdn.net`, which does not include download.vscodium.com.

Perhaps the instructions should be updated to use a different hostname, or the CDN configured to use a different certificate?

Thanks for investigating, and for maintaining VSCodium!
Kevin

**Comment by daiyam** [comment]
CDN hasn't be paid, yet. That's why we get that error.

@PalinuroSec

**Comment by GitMensch** [comment]
As the other issue was closed in favor of this one - I think we need to reopen it, no?

**Comment by daiyam** [comment]
Oops wrong dups: #2279
